---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mariadbs.db.koray.test
spec:
  group: db.koray.test
  names:
    kind: MariaDB
    listKind: MariaDBList
    plural: mariadbs
    singular: mariadb
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MariaDB is the Schema for the mariadbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MariaDB
            properties:
              sshSecret:
                description: Name of the kubernetes secret that contains ssh private and public key (id_rsa and id_rsa.pub) 
                type: string
              cores:
                description: Cores specifies the number of cores the MariaDB VM will have
                type: string
                default: '1'
                pattern: '^(1|2|4|8|16|24|32)$'
              sockets:
                description: Sockets specifies the number of sockets the MariaDB VM will have
                type: string
                default: '1'
                pattern: '^(1|2|4)$'
              memory:
                description: Memory specifies the amount of memory the MariaDB VM will have
                default: 512Mi
                type: string
              running:
                description: Running specifies if the MariaDB VM will be powered on upon creation
                default: true
                type: boolean
              image:
                description: Image specifies container image pull spec of the MariaDB VM
                type: string
                default: quay.io/koray/centos-stream:8
              user:
                description: User specifies the default user that will be created by the cloud-init
                type: string
              password:
                description: If a password is provided, it will be set as the password of the specified user
                type: string
              ports:
                description: Ports specifies the target TCP ports of the MariaDB VM that will be used when defining a k8s service
                type: array
                items:
                  type: integer
                  format: int32
                default:
                - 22
                - 3306
              enableReplication:
                description: Provision specified number of slaves and start database replication
                default: false
                type: boolean
              numberOfSlaves:
                description: Specify the number of slave vms to provision
                default: 1
                minimum: 1
                maximum: 8
                format: int32
                type: integer
              slaveCores:
                description: Specify the number of cores the MariaDB slave VMs will have
                type: string
                default: '1'
                pattern: '^(1|2|4|8|16|24|32)$'
              slaveMemory:
                description: Specify the amount of memory the MariaDB slave VM will have
                default: 512Mi
                type: string
            required:
            - cores
            - memory
            - sshSecret
            - image
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of MariaDB
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
